[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/**"
  to = "https://obscure-sierra-26039-89103941a3f4.herokuapp.com/:splat"
  status = 200
  force = true